version: "3.3"
services:
  ckb:
    image: tockb/ckb-dev:v0.39.2
    ports:
      - "8114:8114"
  ckb-indexer:
    image: tockb/ckb-indexer:ab57116
    ports:
      - "8116:8116"
    environment:
      - RUST_LOG=info
    command: ckb-indexer -s /tmp/ckb-indexer-test -c http://ckb:8114 -l 0.0.0.0:8116
    depends_on:
      - ckb
  godwoken:
    image: godwoken:dev
    volumes:
      - ../:/code
      - cargo-cache:/usr/local/cargo
    # command: tail -F anything
    command: bash /code/entrypoint.sh
    # volumes:
    #   - type: volume
    #     source: geth-dag
    #     target: /root/.ethash
    #   - type: bind
    #     source: ./geth
    #     target: /config
    ports:
      - 8119:8119
    depends_on:
      - postgres
      - ckb
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_DB=lumos
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
  # geth:
  #   image: tockb/geth-priv:v1.9.23

  #   volumes:
  #     - type: volume
  #       source: geth-dag
  #       target: /root/.ethash
  #     - type: bind
  #       source: ./geth
  #       target: /config
  #   ports:
  #     - "8545:8545"

volumes:
  cargo-cache:

# networks:
#   godwoken:
